### ISSUE TITLE
使用您提供的代码报错

### ISSUE THREAD

**Issue by dongshaojia** [zuimeiyujianni/ENAS_micro_retrain_Pytorch#1]
在使用您提供的代码时，在search部分会报错，报错代码为enas_cnn_network.py  line164
self.layers.append(ENASLayer(num_nodes, c_pp, c_p, c_cur, reduction, file_json[reduction]))
TypeError: 'NoneType' object is not subscriptable
报错指的是file_json 这个object，您能给我解答一下吗？万分感谢

**Comment by zuimeiyujianni** [comment]
在使用ENAS_micro_retrain_Pytorch代码时候，首先需要使用NNI的ENAS算法得到搜索出来的网络结构（对应一个json文件，这里对应读入该json文件的操作
https://github.com/zuimeiyujianni/ENAS_micro_retrain_Pytorch/blob/cb26bd4a04d6cd3f11af9b481ab027df2a76ad3a/train_enas_cnn_network.py#L121）我在checkpoint文件夹中保存了对应的json文件，
![image](https://user-images.githubusercontent.com/43957260/106459421-cbc93800-64cc-11eb-9f63-bfd9631d3614.png)

**Comment by dongshaojia** [comment]
> 在使用ENAS_micro_retrain_Pytorch代码的时候，首先需要使用NNI的ENAS算法得到搜索出来的网络结构（对应一个json文件，此处对应读入该json文件的操作）
> https://github.com/zuimeiyujianni/ENAS_micro_retrain_Pytorch/blob/cb26bd4a04d6cd3f11af9b481ab027df2a76ad3a/train_enas_cnn_network.py#L117
> 
> 
> 我在checkpoint文件夹中保存了对应的json文件
> ![图片](https://user-images.githubusercontent.com/43957260/106459421-cbc93800-64cc-11eb-9f63-bfd9631d3614.png)

感谢您的及时回复，我已经明白了。
